// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// sp_new
Rcpp::List sp_new(const int iter, const arma::cube& lambda_varimax, const int q, const int p, const int dim_all_c, const arma::mat& all_c, const arma::mat& lambda_hat, const arma::uvec& st, arma::mat cost_matrix, arma::mat perm);
RcppExport SEXP _EMC2_sp_new(SEXP iterSEXP, SEXP lambda_varimaxSEXP, SEXP qSEXP, SEXP pSEXP, SEXP dim_all_cSEXP, SEXP all_cSEXP, SEXP lambda_hatSEXP, SEXP stSEXP, SEXP cost_matrixSEXP, SEXP permSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type iter(iterSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type lambda_varimax(lambda_varimaxSEXP);
    Rcpp::traits::input_parameter< const int >::type q(qSEXP);
    Rcpp::traits::input_parameter< const int >::type p(pSEXP);
    Rcpp::traits::input_parameter< const int >::type dim_all_c(dim_all_cSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type all_c(all_cSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type lambda_hat(lambda_hatSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type st(stSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type cost_matrix(cost_matrixSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type perm(permSEXP);
    rcpp_result_gen = Rcpp::wrap(sp_new(iter, lambda_varimax, q, p, dim_all_c, all_c, lambda_hat, st, cost_matrix, perm));
    return rcpp_result_gen;
END_RCPP
}
// calculate_subject_means
arma::mat calculate_subject_means(const Rcpp::List& group_designs, const arma::colvec& params);
RcppExport SEXP _EMC2_calculate_subject_means(SEXP group_designsSEXP, SEXP paramsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type group_designs(group_designsSEXP);
    Rcpp::traits::input_parameter< const arma::colvec& >::type params(paramsSEXP);
    rcpp_result_gen = Rcpp::wrap(calculate_subject_means(group_designs, params));
    return rcpp_result_gen;
END_RCPP
}
// draw_alpha_from_design
arma::cube draw_alpha_from_design(const Rcpp::List& group_designs, const arma::mat& mu, const arma::cube& var);
RcppExport SEXP _EMC2_draw_alpha_from_design(SEXP group_designsSEXP, SEXP muSEXP, SEXP varSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type group_designs(group_designsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type var(varSEXP);
    rcpp_result_gen = Rcpp::wrap(draw_alpha_from_design(group_designs, mu, var));
    return rcpp_result_gen;
END_RCPP
}
// dlba
NumericVector dlba(NumericVector t, NumericVector A, NumericVector b, NumericVector v, NumericVector sv, bool posdrift);
RcppExport SEXP _EMC2_dlba(SEXP tSEXP, SEXP ASEXP, SEXP bSEXP, SEXP vSEXP, SEXP svSEXP, SEXP posdriftSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type A(ASEXP);
    Rcpp::traits::input_parameter< NumericVector >::type b(bSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type v(vSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sv(svSEXP);
    Rcpp::traits::input_parameter< bool >::type posdrift(posdriftSEXP);
    rcpp_result_gen = Rcpp::wrap(dlba(t, A, b, v, sv, posdrift));
    return rcpp_result_gen;
END_RCPP
}
// plba
NumericVector plba(NumericVector t, NumericVector A, NumericVector b, NumericVector v, NumericVector sv, bool posdrift);
RcppExport SEXP _EMC2_plba(SEXP tSEXP, SEXP ASEXP, SEXP bSEXP, SEXP vSEXP, SEXP svSEXP, SEXP posdriftSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type A(ASEXP);
    Rcpp::traits::input_parameter< NumericVector >::type b(bSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type v(vSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sv(svSEXP);
    Rcpp::traits::input_parameter< bool >::type posdrift(posdriftSEXP);
    rcpp_result_gen = Rcpp::wrap(plba(t, A, b, v, sv, posdrift));
    return rcpp_result_gen;
END_RCPP
}
// dWald
NumericVector dWald(NumericVector t, NumericVector v, NumericVector B, NumericVector A, NumericVector t0);
RcppExport SEXP _EMC2_dWald(SEXP tSEXP, SEXP vSEXP, SEXP BSEXP, SEXP ASEXP, SEXP t0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type v(vSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type B(BSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type A(ASEXP);
    Rcpp::traits::input_parameter< NumericVector >::type t0(t0SEXP);
    rcpp_result_gen = Rcpp::wrap(dWald(t, v, B, A, t0));
    return rcpp_result_gen;
END_RCPP
}
// pWald
NumericVector pWald(NumericVector t, NumericVector v, NumericVector B, NumericVector A, NumericVector t0);
RcppExport SEXP _EMC2_pWald(SEXP tSEXP, SEXP vSEXP, SEXP BSEXP, SEXP ASEXP, SEXP t0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type v(vSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type B(BSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type A(ASEXP);
    Rcpp::traits::input_parameter< NumericVector >::type t0(t0SEXP);
    rcpp_result_gen = Rcpp::wrap(pWald(t, v, B, A, t0));
    return rcpp_result_gen;
END_RCPP
}
// pEXG
NumericVector pEXG(NumericVector q, double mu, double sigma, double tau, bool lower_tail, bool log_p);
RcppExport SEXP _EMC2_pEXG(SEXP qSEXP, SEXP muSEXP, SEXP sigmaSEXP, SEXP tauSEXP, SEXP lower_tailSEXP, SEXP log_pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type q(qSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< bool >::type lower_tail(lower_tailSEXP);
    Rcpp::traits::input_parameter< bool >::type log_p(log_pSEXP);
    rcpp_result_gen = Rcpp::wrap(pEXG(q, mu, sigma, tau, lower_tail, log_p));
    return rcpp_result_gen;
END_RCPP
}
// dEXG
NumericVector dEXG(NumericVector x, double mu, double sigma, double tau, bool log_d);
RcppExport SEXP _EMC2_dEXG(SEXP xSEXP, SEXP muSEXP, SEXP sigmaSEXP, SEXP tauSEXP, SEXP log_dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< bool >::type log_d(log_dSEXP);
    rcpp_result_gen = Rcpp::wrap(dEXG(x, mu, sigma, tau, log_d));
    return rcpp_result_gen;
END_RCPP
}
// dEXGrace
NumericVector dEXGrace(NumericMatrix dt, NumericVector mu, NumericVector sigma, NumericVector tau);
RcppExport SEXP _EMC2_dEXGrace(SEXP dtSEXP, SEXP muSEXP, SEXP sigmaSEXP, SEXP tauSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type dt(dtSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tau(tauSEXP);
    rcpp_result_gen = Rcpp::wrap(dEXGrace(dt, mu, sigma, tau));
    return rcpp_result_gen;
END_RCPP
}
// stopfn_exg
NumericVector stopfn_exg(NumericVector t, NumericVector mu, NumericVector sigma, NumericVector tau, double SSD);
RcppExport SEXP _EMC2_stopfn_exg(SEXP tSEXP, SEXP muSEXP, SEXP sigmaSEXP, SEXP tauSEXP, SEXP SSDSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< double >::type SSD(SSDSEXP);
    rcpp_result_gen = Rcpp::wrap(stopfn_exg(t, mu, sigma, tau, SSD));
    return rcpp_result_gen;
END_RCPP
}
// pEXG_RDEX
NumericVector pEXG_RDEX(NumericVector q, double mu, double sigma, double tau, bool lower_tail, bool log_p);
RcppExport SEXP _EMC2_pEXG_RDEX(SEXP qSEXP, SEXP muSEXP, SEXP sigmaSEXP, SEXP tauSEXP, SEXP lower_tailSEXP, SEXP log_pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type q(qSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< bool >::type lower_tail(lower_tailSEXP);
    Rcpp::traits::input_parameter< bool >::type log_p(log_pSEXP);
    rcpp_result_gen = Rcpp::wrap(pEXG_RDEX(q, mu, sigma, tau, lower_tail, log_p));
    return rcpp_result_gen;
END_RCPP
}
// dEXG_RDEX
NumericVector dEXG_RDEX(NumericVector x, double mu, double sigma, double tau, bool log_d);
RcppExport SEXP _EMC2_dEXG_RDEX(SEXP xSEXP, SEXP muSEXP, SEXP sigmaSEXP, SEXP tauSEXP, SEXP log_dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< bool >::type log_d(log_dSEXP);
    rcpp_result_gen = Rcpp::wrap(dEXG_RDEX(x, mu, sigma, tau, log_d));
    return rcpp_result_gen;
END_RCPP
}
// pigt0_RDEX
double pigt0_RDEX(double t, double k, double l);
RcppExport SEXP _EMC2_pigt0_RDEX(SEXP tSEXP, SEXP kSEXP, SEXP lSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type l(lSEXP);
    rcpp_result_gen = Rcpp::wrap(pigt0_RDEX(t, k, l));
    return rcpp_result_gen;
END_RCPP
}
// digt0_RDEX
double digt0_RDEX(double t, double k, double l);
RcppExport SEXP _EMC2_digt0_RDEX(SEXP tSEXP, SEXP kSEXP, SEXP lSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type l(lSEXP);
    rcpp_result_gen = Rcpp::wrap(digt0_RDEX(t, k, l));
    return rcpp_result_gen;
END_RCPP
}
// pigt_RDEX
double pigt_RDEX(double t, double k, double l, double a, double threshold);
RcppExport SEXP _EMC2_pigt_RDEX(SEXP tSEXP, SEXP kSEXP, SEXP lSEXP, SEXP aSEXP, SEXP thresholdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type l(lSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type threshold(thresholdSEXP);
    rcpp_result_gen = Rcpp::wrap(pigt_RDEX(t, k, l, a, threshold));
    return rcpp_result_gen;
END_RCPP
}
// digt_RDEX
double digt_RDEX(double t, double k, double l, double a, double threshold);
RcppExport SEXP _EMC2_digt_RDEX(SEXP tSEXP, SEXP kSEXP, SEXP lSEXP, SEXP aSEXP, SEXP thresholdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type l(lSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type threshold(thresholdSEXP);
    rcpp_result_gen = Rcpp::wrap(digt_RDEX(t, k, l, a, threshold));
    return rcpp_result_gen;
END_RCPP
}
// dWald_RDEX
NumericVector dWald_RDEX(NumericVector t, double v, double B, double A, double t0);
RcppExport SEXP _EMC2_dWald_RDEX(SEXP tSEXP, SEXP vSEXP, SEXP BSEXP, SEXP ASEXP, SEXP t0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type v(vSEXP);
    Rcpp::traits::input_parameter< double >::type B(BSEXP);
    Rcpp::traits::input_parameter< double >::type A(ASEXP);
    Rcpp::traits::input_parameter< double >::type t0(t0SEXP);
    rcpp_result_gen = Rcpp::wrap(dWald_RDEX(t, v, B, A, t0));
    return rcpp_result_gen;
END_RCPP
}
// pWald_RDEX
NumericVector pWald_RDEX(NumericVector t, double v, double B, double A, double t0);
RcppExport SEXP _EMC2_pWald_RDEX(SEXP tSEXP, SEXP vSEXP, SEXP BSEXP, SEXP ASEXP, SEXP t0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type v(vSEXP);
    Rcpp::traits::input_parameter< double >::type B(BSEXP);
    Rcpp::traits::input_parameter< double >::type A(ASEXP);
    Rcpp::traits::input_parameter< double >::type t0(t0SEXP);
    rcpp_result_gen = Rcpp::wrap(pWald_RDEX(t, v, B, A, t0));
    return rcpp_result_gen;
END_RCPP
}
// dRDEXrace
NumericVector dRDEXrace(NumericMatrix dt, double mu, double sigma, double tau, NumericVector v, NumericVector B, NumericVector A, NumericVector t0, bool exgWinner);
RcppExport SEXP _EMC2_dRDEXrace(SEXP dtSEXP, SEXP muSEXP, SEXP sigmaSEXP, SEXP tauSEXP, SEXP vSEXP, SEXP BSEXP, SEXP ASEXP, SEXP t0SEXP, SEXP exgWinnerSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type dt(dtSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type v(vSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type B(BSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type A(ASEXP);
    Rcpp::traits::input_parameter< NumericVector >::type t0(t0SEXP);
    Rcpp::traits::input_parameter< bool >::type exgWinner(exgWinnerSEXP);
    rcpp_result_gen = Rcpp::wrap(dRDEXrace(dt, mu, sigma, tau, v, B, A, t0, exgWinner));
    return rcpp_result_gen;
END_RCPP
}
// stopfn_rdex
NumericVector stopfn_rdex(NumericVector t, int n_acc, double mu, double sigma, double tau, NumericVector v, NumericVector B, NumericVector A, NumericVector t0, double SSD);
RcppExport SEXP _EMC2_stopfn_rdex(SEXP tSEXP, SEXP n_accSEXP, SEXP muSEXP, SEXP sigmaSEXP, SEXP tauSEXP, SEXP vSEXP, SEXP BSEXP, SEXP ASEXP, SEXP t0SEXP, SEXP SSDSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< int >::type n_acc(n_accSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type v(vSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type B(BSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type A(ASEXP);
    Rcpp::traits::input_parameter< NumericVector >::type t0(t0SEXP);
    Rcpp::traits::input_parameter< double >::type SSD(SSDSEXP);
    rcpp_result_gen = Rcpp::wrap(stopfn_rdex(t, n_acc, mu, sigma, tau, v, B, A, t0, SSD));
    return rcpp_result_gen;
END_RCPP
}
// fft_convolve_equiv_cpp
arma::vec fft_convolve_equiv_cpp(const arma::vec& x, const arma::vec& y, bool conj_flag);
RcppExport SEXP _EMC2_fft_convolve_equiv_cpp(SEXP xSEXP, SEXP ySEXP, SEXP conj_flagSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< bool >::type conj_flag(conj_flagSEXP);
    rcpp_result_gen = Rcpp::wrap(fft_convolve_equiv_cpp(x, y, conj_flag));
    return rcpp_result_gen;
END_RCPP
}
// compute_gamma_diff_hrf
NumericVector compute_gamma_diff_hrf(double tr, int oversampling, double time_length, double onset, double delay, double undershoot, double dispersion, double u_dispersion, double ratio);
RcppExport SEXP _EMC2_compute_gamma_diff_hrf(SEXP trSEXP, SEXP oversamplingSEXP, SEXP time_lengthSEXP, SEXP onsetSEXP, SEXP delaySEXP, SEXP undershootSEXP, SEXP dispersionSEXP, SEXP u_dispersionSEXP, SEXP ratioSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type tr(trSEXP);
    Rcpp::traits::input_parameter< int >::type oversampling(oversamplingSEXP);
    Rcpp::traits::input_parameter< double >::type time_length(time_lengthSEXP);
    Rcpp::traits::input_parameter< double >::type onset(onsetSEXP);
    Rcpp::traits::input_parameter< double >::type delay(delaySEXP);
    Rcpp::traits::input_parameter< double >::type undershoot(undershootSEXP);
    Rcpp::traits::input_parameter< double >::type dispersion(dispersionSEXP);
    Rcpp::traits::input_parameter< double >::type u_dispersion(u_dispersionSEXP);
    Rcpp::traits::input_parameter< double >::type ratio(ratioSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_gamma_diff_hrf(tr, oversampling, time_length, onset, delay, undershoot, dispersion, u_dispersion, ratio));
    return rcpp_result_gen;
END_RCPP
}
// compute_hrf
NumericVector compute_hrf(double tr, int oversampling, double time_length, double onset, double delay, double undershoot, double dispersion, double u_dispersion, double ratio);
RcppExport SEXP _EMC2_compute_hrf(SEXP trSEXP, SEXP oversamplingSEXP, SEXP time_lengthSEXP, SEXP onsetSEXP, SEXP delaySEXP, SEXP undershootSEXP, SEXP dispersionSEXP, SEXP u_dispersionSEXP, SEXP ratioSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type tr(trSEXP);
    Rcpp::traits::input_parameter< int >::type oversampling(oversamplingSEXP);
    Rcpp::traits::input_parameter< double >::type time_length(time_lengthSEXP);
    Rcpp::traits::input_parameter< double >::type onset(onsetSEXP);
    Rcpp::traits::input_parameter< double >::type delay(delaySEXP);
    Rcpp::traits::input_parameter< double >::type undershoot(undershootSEXP);
    Rcpp::traits::input_parameter< double >::type dispersion(dispersionSEXP);
    Rcpp::traits::input_parameter< double >::type u_dispersion(u_dispersionSEXP);
    Rcpp::traits::input_parameter< double >::type ratio(ratioSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_hrf(tr, oversampling, time_length, onset, delay, undershoot, dispersion, u_dispersion, ratio));
    return rcpp_result_gen;
END_RCPP
}
// compute_time_derivative
NumericVector compute_time_derivative(double tr, int oversampling, double time_length, double onset, double delay, double undershoot, double dispersion, double u_dispersion, double ratio, double delta);
RcppExport SEXP _EMC2_compute_time_derivative(SEXP trSEXP, SEXP oversamplingSEXP, SEXP time_lengthSEXP, SEXP onsetSEXP, SEXP delaySEXP, SEXP undershootSEXP, SEXP dispersionSEXP, SEXP u_dispersionSEXP, SEXP ratioSEXP, SEXP deltaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type tr(trSEXP);
    Rcpp::traits::input_parameter< int >::type oversampling(oversamplingSEXP);
    Rcpp::traits::input_parameter< double >::type time_length(time_lengthSEXP);
    Rcpp::traits::input_parameter< double >::type onset(onsetSEXP);
    Rcpp::traits::input_parameter< double >::type delay(delaySEXP);
    Rcpp::traits::input_parameter< double >::type undershoot(undershootSEXP);
    Rcpp::traits::input_parameter< double >::type dispersion(dispersionSEXP);
    Rcpp::traits::input_parameter< double >::type u_dispersion(u_dispersionSEXP);
    Rcpp::traits::input_parameter< double >::type ratio(ratioSEXP);
    Rcpp::traits::input_parameter< double >::type delta(deltaSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_time_derivative(tr, oversampling, time_length, onset, delay, undershoot, dispersion, u_dispersion, ratio, delta));
    return rcpp_result_gen;
END_RCPP
}
// build_hrf_kernel
NumericMatrix build_hrf_kernel(bool has_derivative, double tr, int oversampling, double time_length, double onset, double delay, double undershoot, double dispersion, double u_dispersion, double ratio);
RcppExport SEXP _EMC2_build_hrf_kernel(SEXP has_derivativeSEXP, SEXP trSEXP, SEXP oversamplingSEXP, SEXP time_lengthSEXP, SEXP onsetSEXP, SEXP delaySEXP, SEXP undershootSEXP, SEXP dispersionSEXP, SEXP u_dispersionSEXP, SEXP ratioSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< bool >::type has_derivative(has_derivativeSEXP);
    Rcpp::traits::input_parameter< double >::type tr(trSEXP);
    Rcpp::traits::input_parameter< int >::type oversampling(oversamplingSEXP);
    Rcpp::traits::input_parameter< double >::type time_length(time_lengthSEXP);
    Rcpp::traits::input_parameter< double >::type onset(onsetSEXP);
    Rcpp::traits::input_parameter< double >::type delay(delaySEXP);
    Rcpp::traits::input_parameter< double >::type undershoot(undershootSEXP);
    Rcpp::traits::input_parameter< double >::type dispersion(dispersionSEXP);
    Rcpp::traits::input_parameter< double >::type u_dispersion(u_dispersionSEXP);
    Rcpp::traits::input_parameter< double >::type ratio(ratioSEXP);
    rcpp_result_gen = Rcpp::wrap(build_hrf_kernel(has_derivative, tr, oversampling, time_length, onset, delay, undershoot, dispersion, u_dispersion, ratio));
    return rcpp_result_gen;
END_RCPP
}
// construct_design_matrix
DataFrame construct_design_matrix(NumericVector frame_times, DataFrame events, bool has_derivative, double min_onset, int oversampling, double time_length, double onset, double delay, double undershoot, double dispersion, double u_dispersion, double ratio, bool add_intercept);
RcppExport SEXP _EMC2_construct_design_matrix(SEXP frame_timesSEXP, SEXP eventsSEXP, SEXP has_derivativeSEXP, SEXP min_onsetSEXP, SEXP oversamplingSEXP, SEXP time_lengthSEXP, SEXP onsetSEXP, SEXP delaySEXP, SEXP undershootSEXP, SEXP dispersionSEXP, SEXP u_dispersionSEXP, SEXP ratioSEXP, SEXP add_interceptSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type frame_times(frame_timesSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type events(eventsSEXP);
    Rcpp::traits::input_parameter< bool >::type has_derivative(has_derivativeSEXP);
    Rcpp::traits::input_parameter< double >::type min_onset(min_onsetSEXP);
    Rcpp::traits::input_parameter< int >::type oversampling(oversamplingSEXP);
    Rcpp::traits::input_parameter< double >::type time_length(time_lengthSEXP);
    Rcpp::traits::input_parameter< double >::type onset(onsetSEXP);
    Rcpp::traits::input_parameter< double >::type delay(delaySEXP);
    Rcpp::traits::input_parameter< double >::type undershoot(undershootSEXP);
    Rcpp::traits::input_parameter< double >::type dispersion(dispersionSEXP);
    Rcpp::traits::input_parameter< double >::type u_dispersion(u_dispersionSEXP);
    Rcpp::traits::input_parameter< double >::type ratio(ratioSEXP);
    Rcpp::traits::input_parameter< bool >::type add_intercept(add_interceptSEXP);
    rcpp_result_gen = Rcpp::wrap(construct_design_matrix(frame_times, events, has_derivative, min_onset, oversampling, time_length, onset, delay, undershoot, dispersion, u_dispersion, ratio, add_intercept));
    return rcpp_result_gen;
END_RCPP
}
// ParamTable_create_from_p_types
SEXP ParamTable_create_from_p_types(int n_trials, CharacterVector p_types);
RcppExport SEXP _EMC2_ParamTable_create_from_p_types(SEXP n_trialsSEXP, SEXP p_typesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n_trials(n_trialsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type p_types(p_typesSEXP);
    rcpp_result_gen = Rcpp::wrap(ParamTable_create_from_p_types(n_trials, p_types));
    return rcpp_result_gen;
END_RCPP
}
// ParamTable_create_from_matrix
SEXP ParamTable_create_from_matrix(NumericMatrix base, CharacterVector names);
RcppExport SEXP _EMC2_ParamTable_create_from_matrix(SEXP baseSEXP, SEXP namesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type base(baseSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type names(namesSEXP);
    rcpp_result_gen = Rcpp::wrap(ParamTable_create_from_matrix(base, names));
    return rcpp_result_gen;
END_RCPP
}
// ParamTable_materialize
NumericMatrix ParamTable_materialize(SEXP pt_xptr);
RcppExport SEXP _EMC2_ParamTable_materialize(SEXP pt_xptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type pt_xptr(pt_xptrSEXP);
    rcpp_result_gen = Rcpp::wrap(ParamTable_materialize(pt_xptr));
    return rcpp_result_gen;
END_RCPP
}
// ParamTable_set_column
void ParamTable_set_column(SEXP pt_xptr, std::string name, NumericVector col);
RcppExport SEXP _EMC2_ParamTable_set_column(SEXP pt_xptrSEXP, SEXP nameSEXP, SEXP colSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type pt_xptr(pt_xptrSEXP);
    Rcpp::traits::input_parameter< std::string >::type name(nameSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type col(colSEXP);
    ParamTable_set_column(pt_xptr, name, col);
    return R_NilValue;
END_RCPP
}
// ParamTable_create_from_pvector_designs
SEXP ParamTable_create_from_pvector_designs(NumericVector p_vector, List designs, int n_trials);
RcppExport SEXP _EMC2_ParamTable_create_from_pvector_designs(SEXP p_vectorSEXP, SEXP designsSEXP, SEXP n_trialsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type p_vector(p_vectorSEXP);
    Rcpp::traits::input_parameter< List >::type designs(designsSEXP);
    Rcpp::traits::input_parameter< int >::type n_trials(n_trialsSEXP);
    rcpp_result_gen = Rcpp::wrap(ParamTable_create_from_pvector_designs(p_vector, designs, n_trials));
    return rcpp_result_gen;
END_RCPP
}
// ParamTable_map_designs
void ParamTable_map_designs(SEXP pt_xptr, Rcpp::List designs, Rcpp::LogicalVector include_param);
RcppExport SEXP _EMC2_ParamTable_map_designs(SEXP pt_xptrSEXP, SEXP designsSEXP, SEXP include_paramSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type pt_xptr(pt_xptrSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type designs(designsSEXP);
    Rcpp::traits::input_parameter< Rcpp::LogicalVector >::type include_param(include_paramSEXP);
    ParamTable_map_designs(pt_xptr, designs, include_param);
    return R_NilValue;
END_RCPP
}
// TrendEngine_create
SEXP TrendEngine_create(SEXP trend, Rcpp::DataFrame data);
RcppExport SEXP _EMC2_TrendEngine_create(SEXP trendSEXP, SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type trend(trendSEXP);
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(TrendEngine_create(trend, data));
    return rcpp_result_gen;
END_RCPP
}
// TrendEngine_premap_mask
LogicalVector TrendEngine_premap_mask(SEXP engine_ptr, List designs);
RcppExport SEXP _EMC2_TrendEngine_premap_mask(SEXP engine_ptrSEXP, SEXP designsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type engine_ptr(engine_ptrSEXP);
    Rcpp::traits::input_parameter< List >::type designs(designsSEXP);
    rcpp_result_gen = Rcpp::wrap(TrendEngine_premap_mask(engine_ptr, designs));
    return rcpp_result_gen;
END_RCPP
}
// ParamTable_get_n_trials
int ParamTable_get_n_trials(SEXP pt_xptr);
RcppExport SEXP _EMC2_ParamTable_get_n_trials(SEXP pt_xptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type pt_xptr(pt_xptrSEXP);
    rcpp_result_gen = Rcpp::wrap(ParamTable_get_n_trials(pt_xptr));
    return rcpp_result_gen;
END_RCPP
}
// ParamTable_do_transform_all
void ParamTable_do_transform_all(SEXP param_table_ptr, Rcpp::List transform);
RcppExport SEXP _EMC2_ParamTable_do_transform_all(SEXP param_table_ptrSEXP, SEXP transformSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type param_table_ptr(param_table_ptrSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type transform(transformSEXP);
    ParamTable_do_transform_all(param_table_ptr, transform);
    return R_NilValue;
END_RCPP
}
// ParamTable_do_transform_premap
void ParamTable_do_transform_premap(SEXP param_table_ptr, SEXP trend_engine_ptr, Rcpp::List transform);
RcppExport SEXP _EMC2_ParamTable_do_transform_premap(SEXP param_table_ptrSEXP, SEXP trend_engine_ptrSEXP, SEXP transformSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type param_table_ptr(param_table_ptrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type trend_engine_ptr(trend_engine_ptrSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type transform(transformSEXP);
    ParamTable_do_transform_premap(param_table_ptr, trend_engine_ptr, transform);
    return R_NilValue;
END_RCPP
}
// ParamTable_do_transform_pretransform
void ParamTable_do_transform_pretransform(SEXP param_table_ptr, SEXP trend_engine_ptr, Rcpp::List transform);
RcppExport SEXP _EMC2_ParamTable_do_transform_pretransform(SEXP param_table_ptrSEXP, SEXP trend_engine_ptrSEXP, SEXP transformSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type param_table_ptr(param_table_ptrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type trend_engine_ptr(trend_engine_ptrSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type transform(transformSEXP);
    ParamTable_do_transform_pretransform(param_table_ptr, trend_engine_ptr, transform);
    return R_NilValue;
END_RCPP
}
// ParamTable_do_transform_posttransform
void ParamTable_do_transform_posttransform(SEXP param_table_ptr, SEXP trend_engine_ptr, Rcpp::List transform);
RcppExport SEXP _EMC2_ParamTable_do_transform_posttransform(SEXP param_table_ptrSEXP, SEXP trend_engine_ptrSEXP, SEXP transformSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type param_table_ptr(param_table_ptrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type trend_engine_ptr(trend_engine_ptrSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type transform(transformSEXP);
    ParamTable_do_transform_posttransform(param_table_ptr, trend_engine_ptr, transform);
    return R_NilValue;
END_RCPP
}
// ParamTable_do_transform_postmap
void ParamTable_do_transform_postmap(SEXP param_table_ptr, SEXP trend_engine_ptr, Rcpp::List transform);
RcppExport SEXP _EMC2_ParamTable_do_transform_postmap(SEXP param_table_ptrSEXP, SEXP trend_engine_ptrSEXP, SEXP transformSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type param_table_ptr(param_table_ptrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type trend_engine_ptr(trend_engine_ptrSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type transform(transformSEXP);
    ParamTable_do_transform_postmap(param_table_ptr, trend_engine_ptr, transform);
    return R_NilValue;
END_RCPP
}
// ParamTable_bind_trendops
void ParamTable_bind_trendops(SEXP param_table_ptr, SEXP trend_engine_ptr);
RcppExport SEXP _EMC2_ParamTable_bind_trendops(SEXP param_table_ptrSEXP, SEXP trend_engine_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type param_table_ptr(param_table_ptrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type trend_engine_ptr(trend_engine_ptrSEXP);
    ParamTable_bind_trendops(param_table_ptr, trend_engine_ptr);
    return R_NilValue;
END_RCPP
}
// TrendEngine_apply_premap_bases
void TrendEngine_apply_premap_bases(SEXP param_table_ptr, SEXP trend_engine_ptr);
RcppExport SEXP _EMC2_TrendEngine_apply_premap_bases(SEXP param_table_ptrSEXP, SEXP trend_engine_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type param_table_ptr(param_table_ptrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type trend_engine_ptr(trend_engine_ptrSEXP);
    TrendEngine_apply_premap_bases(param_table_ptr, trend_engine_ptr);
    return R_NilValue;
END_RCPP
}
// TrendEngine_apply_pretransform_bases
void TrendEngine_apply_pretransform_bases(SEXP param_table_ptr, SEXP trend_engine_ptr);
RcppExport SEXP _EMC2_TrendEngine_apply_pretransform_bases(SEXP param_table_ptrSEXP, SEXP trend_engine_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type param_table_ptr(param_table_ptrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type trend_engine_ptr(trend_engine_ptrSEXP);
    TrendEngine_apply_pretransform_bases(param_table_ptr, trend_engine_ptr);
    return R_NilValue;
END_RCPP
}
// TrendEngine_apply_posttransform_bases
void TrendEngine_apply_posttransform_bases(SEXP param_table_ptr, SEXP trend_engine_ptr);
RcppExport SEXP _EMC2_TrendEngine_apply_posttransform_bases(SEXP param_table_ptrSEXP, SEXP trend_engine_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type param_table_ptr(param_table_ptrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type trend_engine_ptr(trend_engine_ptrSEXP);
    TrendEngine_apply_posttransform_bases(param_table_ptr, trend_engine_ptr);
    return R_NilValue;
END_RCPP
}
// do_transform
Rcpp::NumericMatrix do_transform(Rcpp::NumericMatrix pars, Rcpp::List transform);
RcppExport SEXP _EMC2_do_transform(SEXP parsSEXP, SEXP transformSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type transform(transformSEXP);
    rcpp_result_gen = Rcpp::wrap(do_transform(pars, transform));
    return rcpp_result_gen;
END_RCPP
}
// calc_ll
NumericVector calc_ll(NumericMatrix p_matrix, DataFrame data, NumericVector constants, List designs, String type, List bounds, List transforms, List pretransforms, CharacterVector p_types, double min_ll, Rcpp::Nullable<Rcpp::List> trend);
RcppExport SEXP _EMC2_calc_ll(SEXP p_matrixSEXP, SEXP dataSEXP, SEXP constantsSEXP, SEXP designsSEXP, SEXP typeSEXP, SEXP boundsSEXP, SEXP transformsSEXP, SEXP pretransformsSEXP, SEXP p_typesSEXP, SEXP min_llSEXP, SEXP trendSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type p_matrix(p_matrixSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type data(dataSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type constants(constantsSEXP);
    Rcpp::traits::input_parameter< List >::type designs(designsSEXP);
    Rcpp::traits::input_parameter< String >::type type(typeSEXP);
    Rcpp::traits::input_parameter< List >::type bounds(boundsSEXP);
    Rcpp::traits::input_parameter< List >::type transforms(transformsSEXP);
    Rcpp::traits::input_parameter< List >::type pretransforms(pretransformsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type p_types(p_typesSEXP);
    Rcpp::traits::input_parameter< double >::type min_ll(min_llSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::List> >::type trend(trendSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_ll(p_matrix, data, constants, designs, type, bounds, transforms, pretransforms, p_types, min_ll, trend));
    return rcpp_result_gen;
END_RCPP
}
// calc_ll_oo
NumericVector calc_ll_oo(NumericMatrix particle_matrix, DataFrame data, NumericVector constants, List designs, String type, List bounds, List transforms, List pretransforms, CharacterVector p_types, double min_ll, Rcpp::Nullable<Rcpp::List> trend);
RcppExport SEXP _EMC2_calc_ll_oo(SEXP particle_matrixSEXP, SEXP dataSEXP, SEXP constantsSEXP, SEXP designsSEXP, SEXP typeSEXP, SEXP boundsSEXP, SEXP transformsSEXP, SEXP pretransformsSEXP, SEXP p_typesSEXP, SEXP min_llSEXP, SEXP trendSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type particle_matrix(particle_matrixSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type data(dataSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type constants(constantsSEXP);
    Rcpp::traits::input_parameter< List >::type designs(designsSEXP);
    Rcpp::traits::input_parameter< String >::type type(typeSEXP);
    Rcpp::traits::input_parameter< List >::type bounds(boundsSEXP);
    Rcpp::traits::input_parameter< List >::type transforms(transformsSEXP);
    Rcpp::traits::input_parameter< List >::type pretransforms(pretransformsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type p_types(p_typesSEXP);
    Rcpp::traits::input_parameter< double >::type min_ll(min_llSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::List> >::type trend(trendSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_ll_oo(particle_matrix, data, constants, designs, type, bounds, transforms, pretransforms, p_types, min_ll, trend));
    return rcpp_result_gen;
END_RCPP
}
// get_pars_c_wrapper
NumericMatrix get_pars_c_wrapper(NumericMatrix p_matrix, DataFrame data, NumericVector constants, List designs, List bounds, List transforms, List pretransforms, CharacterVector p_types, Rcpp::Nullable<Rcpp::List> trend, bool return_kernel_matrix, bool drop_trend_pars);
RcppExport SEXP _EMC2_get_pars_c_wrapper(SEXP p_matrixSEXP, SEXP dataSEXP, SEXP constantsSEXP, SEXP designsSEXP, SEXP boundsSEXP, SEXP transformsSEXP, SEXP pretransformsSEXP, SEXP p_typesSEXP, SEXP trendSEXP, SEXP return_kernel_matrixSEXP, SEXP drop_trend_parsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type p_matrix(p_matrixSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type data(dataSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type constants(constantsSEXP);
    Rcpp::traits::input_parameter< List >::type designs(designsSEXP);
    Rcpp::traits::input_parameter< List >::type bounds(boundsSEXP);
    Rcpp::traits::input_parameter< List >::type transforms(transformsSEXP);
    Rcpp::traits::input_parameter< List >::type pretransforms(pretransformsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type p_types(p_typesSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::List> >::type trend(trendSEXP);
    Rcpp::traits::input_parameter< bool >::type return_kernel_matrix(return_kernel_matrixSEXP);
    Rcpp::traits::input_parameter< bool >::type drop_trend_pars(drop_trend_parsSEXP);
    rcpp_result_gen = Rcpp::wrap(get_pars_c_wrapper(p_matrix, data, constants, designs, bounds, transforms, pretransforms, p_types, trend, return_kernel_matrix, drop_trend_pars));
    return rcpp_result_gen;
END_RCPP
}
// get_pars_c_wrapper_oo
NumericMatrix get_pars_c_wrapper_oo(NumericMatrix particle_matrix, DataFrame data, NumericVector constants, List designs, List bounds, List transforms, List pretransforms, Rcpp::Nullable<Rcpp::List> trend, bool return_kernel_matrix, bool return_all_pars);
RcppExport SEXP _EMC2_get_pars_c_wrapper_oo(SEXP particle_matrixSEXP, SEXP dataSEXP, SEXP constantsSEXP, SEXP designsSEXP, SEXP boundsSEXP, SEXP transformsSEXP, SEXP pretransformsSEXP, SEXP trendSEXP, SEXP return_kernel_matrixSEXP, SEXP return_all_parsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type particle_matrix(particle_matrixSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type data(dataSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type constants(constantsSEXP);
    Rcpp::traits::input_parameter< List >::type designs(designsSEXP);
    Rcpp::traits::input_parameter< List >::type bounds(boundsSEXP);
    Rcpp::traits::input_parameter< List >::type transforms(transformsSEXP);
    Rcpp::traits::input_parameter< List >::type pretransforms(pretransformsSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::List> >::type trend(trendSEXP);
    Rcpp::traits::input_parameter< bool >::type return_kernel_matrix(return_kernel_matrixSEXP);
    Rcpp::traits::input_parameter< bool >::type return_all_pars(return_all_parsSEXP);
    rcpp_result_gen = Rcpp::wrap(get_pars_c_wrapper_oo(particle_matrix, data, constants, designs, bounds, transforms, pretransforms, trend, return_kernel_matrix, return_all_pars));
    return rcpp_result_gen;
END_RCPP
}
// EMC2_call_custom_trend
NumericVector EMC2_call_custom_trend(NumericMatrix trend_pars, NumericMatrix input, SEXP funptrSEXP);
RcppExport SEXP _EMC2_EMC2_call_custom_trend(SEXP trend_parsSEXP, SEXP inputSEXP, SEXP funptrSEXPSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type trend_pars(trend_parsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type input(inputSEXP);
    Rcpp::traits::input_parameter< SEXP >::type funptrSEXP(funptrSEXPSEXP);
    rcpp_result_gen = Rcpp::wrap(EMC2_call_custom_trend(trend_pars, input, funptrSEXP));
    return rcpp_result_gen;
END_RCPP
}
// run_trend_rcpp
NumericVector run_trend_rcpp(DataFrame data, List trend, NumericVector param, NumericMatrix trend_pars, NumericMatrix pars_full, bool return_kernel);
RcppExport SEXP _EMC2_run_trend_rcpp(SEXP dataSEXP, SEXP trendSEXP, SEXP paramSEXP, SEXP trend_parsSEXP, SEXP pars_fullSEXP, SEXP return_kernelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type data(dataSEXP);
    Rcpp::traits::input_parameter< List >::type trend(trendSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type param(paramSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type trend_pars(trend_parsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type pars_full(pars_fullSEXP);
    Rcpp::traits::input_parameter< bool >::type return_kernel(return_kernelSEXP);
    rcpp_result_gen = Rcpp::wrap(run_trend_rcpp(data, trend, param, trend_pars, pars_full, return_kernel));
    return rcpp_result_gen;
END_RCPP
}
// c_add_charvectors
CharacterVector c_add_charvectors(CharacterVector x, CharacterVector y);
RcppExport SEXP _EMC2_c_add_charvectors(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(c_add_charvectors(x, y));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_EMC2_sp_new", (DL_FUNC) &_EMC2_sp_new, 10},
    {"_EMC2_calculate_subject_means", (DL_FUNC) &_EMC2_calculate_subject_means, 2},
    {"_EMC2_draw_alpha_from_design", (DL_FUNC) &_EMC2_draw_alpha_from_design, 3},
    {"_EMC2_dlba", (DL_FUNC) &_EMC2_dlba, 6},
    {"_EMC2_plba", (DL_FUNC) &_EMC2_plba, 6},
    {"_EMC2_dWald", (DL_FUNC) &_EMC2_dWald, 5},
    {"_EMC2_pWald", (DL_FUNC) &_EMC2_pWald, 5},
    {"_EMC2_pEXG", (DL_FUNC) &_EMC2_pEXG, 6},
    {"_EMC2_dEXG", (DL_FUNC) &_EMC2_dEXG, 5},
    {"_EMC2_dEXGrace", (DL_FUNC) &_EMC2_dEXGrace, 4},
    {"_EMC2_stopfn_exg", (DL_FUNC) &_EMC2_stopfn_exg, 5},
    {"_EMC2_pEXG_RDEX", (DL_FUNC) &_EMC2_pEXG_RDEX, 6},
    {"_EMC2_dEXG_RDEX", (DL_FUNC) &_EMC2_dEXG_RDEX, 5},
    {"_EMC2_pigt0_RDEX", (DL_FUNC) &_EMC2_pigt0_RDEX, 3},
    {"_EMC2_digt0_RDEX", (DL_FUNC) &_EMC2_digt0_RDEX, 3},
    {"_EMC2_pigt_RDEX", (DL_FUNC) &_EMC2_pigt_RDEX, 5},
    {"_EMC2_digt_RDEX", (DL_FUNC) &_EMC2_digt_RDEX, 5},
    {"_EMC2_dWald_RDEX", (DL_FUNC) &_EMC2_dWald_RDEX, 5},
    {"_EMC2_pWald_RDEX", (DL_FUNC) &_EMC2_pWald_RDEX, 5},
    {"_EMC2_dRDEXrace", (DL_FUNC) &_EMC2_dRDEXrace, 9},
    {"_EMC2_stopfn_rdex", (DL_FUNC) &_EMC2_stopfn_rdex, 10},
    {"_EMC2_fft_convolve_equiv_cpp", (DL_FUNC) &_EMC2_fft_convolve_equiv_cpp, 3},
    {"_EMC2_compute_gamma_diff_hrf", (DL_FUNC) &_EMC2_compute_gamma_diff_hrf, 9},
    {"_EMC2_compute_hrf", (DL_FUNC) &_EMC2_compute_hrf, 9},
    {"_EMC2_compute_time_derivative", (DL_FUNC) &_EMC2_compute_time_derivative, 10},
    {"_EMC2_build_hrf_kernel", (DL_FUNC) &_EMC2_build_hrf_kernel, 10},
    {"_EMC2_construct_design_matrix", (DL_FUNC) &_EMC2_construct_design_matrix, 13},
    {"_EMC2_ParamTable_create_from_p_types", (DL_FUNC) &_EMC2_ParamTable_create_from_p_types, 2},
    {"_EMC2_ParamTable_create_from_matrix", (DL_FUNC) &_EMC2_ParamTable_create_from_matrix, 2},
    {"_EMC2_ParamTable_materialize", (DL_FUNC) &_EMC2_ParamTable_materialize, 1},
    {"_EMC2_ParamTable_set_column", (DL_FUNC) &_EMC2_ParamTable_set_column, 3},
    {"_EMC2_ParamTable_create_from_pvector_designs", (DL_FUNC) &_EMC2_ParamTable_create_from_pvector_designs, 3},
    {"_EMC2_ParamTable_map_designs", (DL_FUNC) &_EMC2_ParamTable_map_designs, 3},
    {"_EMC2_TrendEngine_create", (DL_FUNC) &_EMC2_TrendEngine_create, 2},
    {"_EMC2_TrendEngine_premap_mask", (DL_FUNC) &_EMC2_TrendEngine_premap_mask, 2},
    {"_EMC2_ParamTable_get_n_trials", (DL_FUNC) &_EMC2_ParamTable_get_n_trials, 1},
    {"_EMC2_ParamTable_do_transform_all", (DL_FUNC) &_EMC2_ParamTable_do_transform_all, 2},
    {"_EMC2_ParamTable_do_transform_premap", (DL_FUNC) &_EMC2_ParamTable_do_transform_premap, 3},
    {"_EMC2_ParamTable_do_transform_pretransform", (DL_FUNC) &_EMC2_ParamTable_do_transform_pretransform, 3},
    {"_EMC2_ParamTable_do_transform_posttransform", (DL_FUNC) &_EMC2_ParamTable_do_transform_posttransform, 3},
    {"_EMC2_ParamTable_do_transform_postmap", (DL_FUNC) &_EMC2_ParamTable_do_transform_postmap, 3},
    {"_EMC2_ParamTable_bind_trendops", (DL_FUNC) &_EMC2_ParamTable_bind_trendops, 2},
    {"_EMC2_TrendEngine_apply_premap_bases", (DL_FUNC) &_EMC2_TrendEngine_apply_premap_bases, 2},
    {"_EMC2_TrendEngine_apply_pretransform_bases", (DL_FUNC) &_EMC2_TrendEngine_apply_pretransform_bases, 2},
    {"_EMC2_TrendEngine_apply_posttransform_bases", (DL_FUNC) &_EMC2_TrendEngine_apply_posttransform_bases, 2},
    {"_EMC2_do_transform", (DL_FUNC) &_EMC2_do_transform, 2},
    {"_EMC2_calc_ll", (DL_FUNC) &_EMC2_calc_ll, 11},
    {"_EMC2_calc_ll_oo", (DL_FUNC) &_EMC2_calc_ll_oo, 11},
    {"_EMC2_get_pars_c_wrapper", (DL_FUNC) &_EMC2_get_pars_c_wrapper, 11},
    {"_EMC2_get_pars_c_wrapper_oo", (DL_FUNC) &_EMC2_get_pars_c_wrapper_oo, 10},
    {"_EMC2_EMC2_call_custom_trend", (DL_FUNC) &_EMC2_EMC2_call_custom_trend, 3},
    {"_EMC2_run_trend_rcpp", (DL_FUNC) &_EMC2_run_trend_rcpp, 6},
    {"_EMC2_c_add_charvectors", (DL_FUNC) &_EMC2_c_add_charvectors, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_EMC2(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
