# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sp_new <- function(iter, lambda_varimax, q, p, dim_all_c, all_c, lambda_hat, st, cost_matrix, perm) {
    .Call(`_EMC2_sp_new`, iter, lambda_varimax, q, p, dim_all_c, all_c, lambda_hat, st, cost_matrix, perm)
}

dlba <- function(t, A, b, v, sv, posdrift = TRUE) {
    .Call(`_EMC2_dlba`, t, A, b, v, sv, posdrift)
}

plba <- function(t, A, b, v, sv, posdrift = TRUE) {
    .Call(`_EMC2_plba`, t, A, b, v, sv, posdrift)
}

dWald <- function(t, v, B, A, t0) {
    .Call(`_EMC2_dWald`, t, v, B, A, t0)
}

pWald <- function(t, v, B, A, t0) {
    .Call(`_EMC2_pWald`, t, v, B, A, t0)
}

fft_convolve_equiv_cpp <- function(x, y, conj_flag = TRUE) {
    .Call(`_EMC2_fft_convolve_equiv_cpp`, x, y, conj_flag)
}

compute_gamma_diff_hrf <- function(tr, oversampling, time_length, onset, delay, undershoot, dispersion, u_dispersion, ratio) {
    .Call(`_EMC2_compute_gamma_diff_hrf`, tr, oversampling, time_length, onset, delay, undershoot, dispersion, u_dispersion, ratio)
}

compute_hrf <- function(tr, oversampling, time_length, onset, delay, undershoot, dispersion, u_dispersion, ratio) {
    .Call(`_EMC2_compute_hrf`, tr, oversampling, time_length, onset, delay, undershoot, dispersion, u_dispersion, ratio)
}

compute_time_derivative <- function(tr, oversampling, time_length, onset, delay, undershoot, dispersion, u_dispersion, ratio, delta = 0.1) {
    .Call(`_EMC2_compute_time_derivative`, tr, oversampling, time_length, onset, delay, undershoot, dispersion, u_dispersion, ratio, delta)
}

build_hrf_kernel <- function(has_derivative, tr, oversampling, time_length, onset, delay, undershoot, dispersion, u_dispersion, ratio) {
    .Call(`_EMC2_build_hrf_kernel`, has_derivative, tr, oversampling, time_length, onset, delay, undershoot, dispersion, u_dispersion, ratio)
}

construct_design_matrix <- function(frame_times, events, has_derivative, min_onset, oversampling, time_length, onset, delay, undershoot, dispersion, u_dispersion, ratio, add_intercept) {
    .Call(`_EMC2_construct_design_matrix`, frame_times, events, has_derivative, min_onset, oversampling, time_length, onset, delay, undershoot, dispersion, u_dispersion, ratio, add_intercept)
}

calc_ll <- function(p_matrix, data, constants, designs, type, bounds, transforms, pretransforms, p_types, min_ll, trend) {
    .Call(`_EMC2_calc_ll`, p_matrix, data, constants, designs, type, bounds, transforms, pretransforms, p_types, min_ll, trend)
}

c_add_charvectors <- function(x, y) {
    .Call(`_EMC2_c_add_charvectors`, x, y)
}

